### ISSUE TITLE
API hanging

### ISSUE THREAD

**Issue by logonnaidoo2020** [tirnovar/Power-BI-Admin-REST-API-Connector#9]
Hello
Have you found the issue because it hangs sometimes or get stuck when trying to load data.
When will you a newer version of this API

**Comment by tirnovar** [comment]
Hey, this happened when you exceeded the API limit. Someone else in your company can also exceed the limit because most of these endpoints have shared limits. 

I am not planning a new version of this connector because I am working on a PySpark solution for Microsoft Fabric. After publishing this, I might add new features to this connector. If you have an idea of what you would like to add, please share it with me as a pull request.
